### ISSUE TITLE
Devices are not visible anymore from yesterday afternoon

### ISSUE THREAD

**Issue by Zciwobukaj** [1activegeek/docker-airconnect#11]
Hi,
yesterday you performed many commits and things worked well until yesterday afternoon.
I didn't change anything neither on my airconnect docker container, nor in my network environment.

Thanks in advance

**Comment by 1activegeek** [comment]
Thanks for the note. Are you seeing any errors from the container logs? And can you share, are you using any of the variables? 

The updates performed were for introducing multi-arch options. There was an accidental update that pushed the test version to the latest tag, but I corrected that after I recognized it. Since then both versions are now the same and were tested by myself and others running various versions of the app.

**Comment by adammccrory** [comment]
I just installed this and no devices are appearing

Logs here 
https://pastebin.com/0f1rQUdz

**Comment by Zciwobukaj** [comment]
@1activegeek : devices were finally back without any action from my side, and from few days they are still here. I guess we can close the issue.

@adammccrory : while setting up your Docker container, did you put it on host network ?

**Comment by adammccrory** [comment]
Yes, ran it as docker run --net=host 1activegeek/airconnect

**Comment by 1activegeek** [comment]
@Zciwobukaj glad to see things are running smoothly again. I would guess there must have been some sort of connectivity or network snafu as the core components for normal x86_64 users did not change during this update. 

@adammccrory thanks for the logs, by what you have there the container is running and operating as expected. When you get the final two lines there:
```
2020-04-20 10:50:36,919 INFO success: airupnp-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-20 10:50:36,919 INFO success: aircast-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
This is an indication that the services have entered the running state and are staying up. If that has completed, your issue would lie either in the configuration being used (reliance on special inputs or altered configuration) or something else in your network configuration perhaps. Sorry I can't be of much more help. I'll close this issue for now as the OP issue is resolved. If there is a further issue @adammccrory that you identify with the container (please be aware I don't write the application) then please feel free to open a new issue.
