### ISSUE TITLE
Airplay not working 

### ISSUE THREAD

**Issue by johnmehan** [1activegeek/docker-airconnect#13]
Running 

docker run -d --net=host 1activegeek/airconnect

fails to make sonos speakers available for airplay.  It looks like airupnp is binding to the internal docker ip and is ignoring the --net host flag. 

Might be something introduced in https://github.com/philippe44/AirConnect

**Comment by johnmehan** [comment]
I manage to get it to work but doing the following

docker run -d --net host --env AIRUPNP_VAR="-b 192.168.1.60" 1activegeek/airconnect

I had to specify my hosts IP using the -b parameter.

**Comment by 1activegeek** [comment]
I'm glad you got it working, I can't necessarily speak to the intricacies of having to specify the host. I've had it working without, but I don't have Sonos. There are also network configurations at play here that can cause different issues. I would suggest following this up on the AirConnect issue list if you want to pursue a bit further. There isn't anything about the docking setup that I'm aware of that will affect the IP being reported or shown from the script as I'm not setting any type of bind configs anywhere in the dockerfile or startup scripts.

**Comment by x5nder** [comment]
Same here; one of the updates early May broke the '--net=host' functionality, you now have to manually specify the host IP with AIRUPNP_VAR as mentioned by johnmehan.
