### ISSUE TITLE
Run this on QNAP witch Intel Celeron CPU

### ISSUE THREAD

**Issue by crozo5** [1activegeek/docker-airconnect#16]
I have a QNAP NAS with an Intel Celeron CPU, I am trying to install this docker through Container Station with network HOST, but I cannot find any Chromecast or Google Home device. I have seen that this docker is made for arm, arm64 and amd64. I don't know if there is the problem.

**Comment by 1activegeek** [comment]
I can't exclusively comment on the architecture as I'm not 100% sure, but I'm fairly certain that would be operating on the standard image with no architecture specification need as it is a standard x86-64 chip. I would say it's likely that there is something else going on relative to your network configuration potentially blocking devices from seeing the container. Unfortunately, I can't help as much there and don't have that expertise. Please check out the original project for help on troubleshooting or identifying potential solutions for the lack of connectivity. I'm simply the maintainer of the container setup to run the app, beyond that I can't help as much. Sorry.

**Comment by crozo5** [comment]
This is my LOG:

```
[cont-init.d] 30-install: exited 1.                                                                                                                          
[cont-init.d] 99-custom-scripts: executing...                                                                                                                
[custom-init] no custom files found exiting...                                                                                                               
[cont-init.d] 99-custom-scripts: exited 0.                                                                                                                   
[cont-init.d] done.                                                                                                                                          
[services.d] starting services                                                                                                                               
[services.d] done.                                                                                                                                           
2020-10-19 14:50:45,919 CRIT Supervisor running as root (no user in config file)                                                                             
2020-10-19 14:50:45,936 INFO supervisord started with pid 261                                                                                                
2020-10-19 14:50:46,938 INFO spawned: 'airupnp-x86-64' with pid 273                                                                                          
2020-10-19 14:50:46,947 INFO spawned: 'aircast-x86-64' with pid 274                                                                                          
2020-10-19 14:50:48,160 INFO success: airupnp-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                           
2020-10-19 14:50:48,160 INFO success: aircast-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)  
```

In case it can help.

**Comment by 1activegeek** [comment]
Yes, as I said above this is not something about the container. This is something relative to your network and configuration of the environment you are running in. That log indicates that the container I've created is working exactly as expected, and properly. Please check out the source project for help in figuring out why you are not seeing the devices. 

To be clear - there is nothing I can assist with further - the container is working as expected and has no indicated errors.
