### ISSUE TITLE
Custom Config File - Opening Ports to cross VLANs

### ISSUE THREAD

**Issue by Flyinace2000** [1activegeek/docker-airconnect#20]
I was troubleshooting a firewall issue over on the main project page, but now I think my question goes here.  

I generated the below config for the current setup.  The ports were set to 0:0 and I thought that a 150 open ports would be more than enough for 6 or 7 devices. saved the file as config.xml and placed back into the /config folder inside the docker.  

Then I updated my firewall rules.  Back to no sound again.    If I restore the firewall rule to open 32768-61000 everything works.  So I've done something wrong.  Any help would be appreciated.  Thank You

```
<?xml version="1.0"?>
<aircast>
<common>
<enabled>1</enabled>
<stop_receiver>0</stop_receiver>
<media_volume>0.5000</media_volume>
<latency></latency>
<drift>0</drift>
<codec>flc</codec>
<metadata>1</metadata>
<artwork></artwork>
</common>
<main_log>info</main_log>
<cast_log>info</cast_log>
<util_log>warn</util_log>
<log_limit>-1</log_limit>
<max_players>32</max_players>
<ports>60100:60250</ports>
<device>
```

![Screen Shot 2020-12-13 at 9 23 12 PM](https://user-images.githubusercontent.com/6023562/102034439-fed43280-3d8b-11eb-9692-bd0807d8190c.png)

**Comment by Flyinace2000** [comment]
More detail:
OS: UnRaid 6.8.3
i3-9100

**Comment by 1activegeek** [comment]
I'm not sure there is much I can help you with from the container side. It sounds like the change you tried to make, is not working for streaming. If the config was accepted and working, then there is something wrong with the configuration you are setting I would believe. It sounds like the container is operating as intended, but you are not successful in what you are trying to configure - which unfortunately falls outside my scope of expertise.

**Comment by 1activegeek** [comment]
Just one thing I'll add in as an afterthought which could be partly to blame - though I think by now you've already done - try doing a fresh docker pull on the airconnect container. If you were using an image that is over a week old, it is possible that you are not running the latest version of airconnect. I recall he mentioned in the other issue 2.4.x, which is only a version within the last week. My container updates to his latest code weekly - it was just updated recently 2 days ago which should have a 2.4.x version.

**Comment by Flyinace2000** [comment]
Alright so just to confirm.  Do I need to do anything special w/ the docker settings (variables etc) to make it use the custom config or just the existence of the config.xml is enough?

**Comment by Flyinace2000** [comment]
Ok re-read your documentation.  I think I used the AIRCAST_VAR to make the container pass the -x /config.xml

![Screen Shot 2020-12-14 at 8 21 12 PM](https://user-images.githubusercontent.com/6023562/102155911-75d00080-3e4a-11eb-9107-e07cc717a391.png)

![Screen Shot 2020-12-14 at 8 20 50 PM](https://user-images.githubusercontent.com/6023562/102155915-7799c400-3e4a-11eb-90bf-19c97a543050.png)

**Comment by 1activegeek** [comment]
Ya correct, you will need the `-x /file/location/config.xml`. Keep in mind you may need to mount that file as well with a variable as a path to the file.

**Comment by Flyinace2000** [comment]
> Ya correct, you will need the `-x /file/location/config.xml`. Keep in mind you may need to mount that file as well with a variable as a path to the file.

So the config.xml i created is at the root level of the container (and in the /config/ folder cause i just wasn’t sure where the right spot was :-).  Given that the config.xml lives inside the container would i still need to mount the file as a variable? (I don’t think so, but I’m obviously new to this).

Thanks in advanced.

**Comment by Flyinace2000** [comment]
Would the correct path be “docker AirConnect:/config.xml” or am i doing this wrong :-)

**Comment by 1activegeek** [comment]
When you are mounting files from the local system inside the container, it would need to be something in the format of `-v /location/on/local/host/file.ext:/location/inside/container/file.ext`. You mentioned unRAID I believe - so you can just input it like so:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/6810720/102172677-3fed4500-3e67-11eb-96c2-2bbc6e7382f1.png">

**Comment by Flyinace2000** [comment]
Ok that makes sense.  I created a folder in appdata to store the config.xml file.  then i did the mapping.  Then updated AirCast_VAR to be “-x /config.xml”.  That seems to have broken things further and i can’t even connect to the devices (though they do show up in the list).
![4522F2CA-CD96-4F95-B39C-525FBFD285A3](https://user-images.githubusercontent.com/6023562/102234698-8c646f00-3ebf-11eb-82be-2ef386a4899d.jpeg)

**Comment by 1activegeek** [comment]
That looks right. I saw your post on the orig dev issues. Hopefully it's just the XML format that can fix it up.

**Comment by Flyinace2000** [comment]
I'm closing this issue as it is not related to the container setup.  Can I recommend that the readme explains that you can create the AIRCAST_VAR to place the different options for AirConnect? 

Thanks for the help.

**Comment by 1activegeek** [comment]
Thanks for circling back. I'm not sure I understand what you mean on the readme though, is this not explained here:

<img width="934" alt="Screen Shot 2020-12-15 at 11 53 05 PM" src="https://user-images.githubusercontent.com/6810720/102306712-d9ccf480-3f30-11eb-9d39-97fb9b291ff6.png">

**Comment by Flyinace2000** [comment]
Yeah I guess so, I guess it was my (lack of) understanding that the container "AirConnect" included to applications, one for casting and one fore UPNP.  Maybe just a screenshot showing an example of the two variables within UnRaid (or similar)?

Thanks for all the help.
