### ISSUE TITLE
airconnect failing after several hours

### ISSUE THREAD

**Issue by Juggler00** [1activegeek/docker-airconnect#21]
Running the latest version of your container on Ubuntu 20.04 using docker-compose. Several hours after starting the container, mDNS no longer sees the advertisements for my Chromecasts that airconnect surfaces. On restarting the container, they re-appear. 

Looking at the log surfaced through Portainer, there is no error messages thrown. I have connected to the container and poked through the /var/log directory, but don't see any other logs being used.

Is anyone else experiencing this? Would appreciate any help trying to debug this issue.

**Comment by 1activegeek** [comment]
I've not seen this as an issue. My devices show up and have been running in containers that have been running for weeks on end with no loss of device broadcasts on the network. I'd say if something is changing after time, you may have a scenario of networking getting in the way. Could be at the docker level, could be at the host level, or could be at your physical network layer (aka your router/switching stack). As you indicated, logs are not indicating any errors/issues, the service still looks to be up, so I would rule out the container/app being the source of the issue.

**Comment by 1activegeek** [comment]
Losing as stale issue, and no apparent issue by anyone else.
