### ISSUE TITLE
Editing Config with a CLI only version of Ubuntu

### ISSUE THREAD

**Issue by kats1123** [1activegeek/docker-airconnect#22]
Where is the config file located for this, when the command (during setup) is run from ~

Goal is to use IP address targeting to select only my sonos speaker, instead of seeing 5 tv's in airplays options.

**Comment by 1activegeek** [comment]
Not quite sure what you mean by the command run from during setup - the container is going to run the command as it has been programmed. If you need to change the run command, or add a config file, you can use the `_VAR` entries in the docker run command. If you want to map the config file, then pass the config file in with the mapping in the docker run command. Then use the appropriate `_VAR` command. If you don't map a config, there is no config file and it operates on an auto discovery nature. If you'd like to generate a sample config files, see the original repo documentation on creating a config file - again, leveraging the appropriate `_VAR` command for your needs.

**Comment by kats1123** [comment]
Ok so, I’m not the best with command line, especially on Ubuntu, so I’ll try to explain better. After SSH’ing into it, installing docker, I ran “ docker run -d --net=host 1activegeek/airconnect” first time it downloaded and decompiled all the parts second time it actually ran it. Where is the config file that it is using when I run that command, or is it even using a config file?

**Comment by 1activegeek** [comment]
It is not using a config file in that scenario. Per my previous message, you need to use the container variables to specify a config file. You would need to map the config file as part of your docker run command, then specify it in the respective `_VAR` Environment variable. This will then tell the binary to launch with your specified config. Take a peak through the readme here as that process is described within. If you need assistance in how to run docker containers with additional variables and/or mapping local files such as the config file into a container, take a look through the docker documentation as it is quite extensive with examples to help you out.

**Comment by 1activegeek** [comment]
Closing for stale issue.
