### ISSUE TITLE
--net=host is not supported on either Mac or Windows.

### ISSUE THREAD

**Issue by mattahorton** [1activegeek/docker-airconnect#28]
[According to Docker's official documentation](https://docs.docker.com/network/host/) --net=host will never work on Docker for Mac or Windows due to platform limitations. This means even adding an AIRCAST_VAR="-b $hostip" will not work because the port is not exposed to Docker.

What are the appropriate ports we need to map using -p to get this to work?

**Comment by 1activegeek** [comment]
I'm not sure I can tell you that. you will likely want to search through the original app documentation I have linked to identify. I believe there have been issues opened about ports. Based on the very nature of UPnP and mDNS though, I'm not sure it's a matter of a single port even, it may be ranges of ports at the very least.

**Comment by Enzime** [comment]
From the AirConnect README:

> In Docker, you must use 'host' mode to enable audio webserver. Note that you can't have a NAT between your devices and the machine where AirConnect runs."

**Comment by 1activegeek** [comment]
Closing this issue as stale as this is not related to the container.
