### ISSUE TITLE
Will this start automatically after reboot?

### ISSUE THREAD

**Issue by muammar** [1activegeek/docker-airconnect#30]
Thanks for putting together this docker image. I wonder if this will automatically start after reboot?

I run it using: 

```
docker run -d --net=host 1activegeek/airconnect
```

**Comment by 1activegeek** [comment]
If you are new to docker, please consult docker documentation. Closing as this is not an issue with the container.

https://lmgtfy.app/?q=start+docker+container+after+reboot
