### ISSUE TITLE
ARCH_VAR from x86-64 to amd64, can't get executable file from github, please change it back

### ISSUE THREAD

**Issue by lollyhero** [1activegeek/docker-airconnect#33]
FYI,

when i change amd64 to x86-64, everything goes well.

**Comment by 1activegeek** [comment]
Not sure I understand what you are saying here? The current build is working fine. All that was changed was the dockerfile needed to be updated for the image that was used since the original image being used no longer existed with the x86-64 tag. I've validated the updated image works fine and can download the executable fine (and it should since this did not change). No changes were needed by any user and this has nothing to do with the executable and it's configurations.

Bottom line, nothing was changed that should affect any user in how they were using this container. If there is an issue you are seeing, please share more details as your issue isn't making sense. 

Specifically: 
> when i change amd64 to x86-64, everything goes well.
Where are you changing this? And why? 

Example of container running perfectly fine via compose:
```
  airconnect:
    container_name: airconnect
    hostname: airconnect
    image: 1activegeek/airconnect
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=$TZ
      - ARCH_VAR=x86-64
```

```
user@server:~$ cd /volume2/docker/
user@server:/volume2/docker$ docker-compose pull airconnect
WARNING: Some networks were defined but are not used by any service: host
Pulling airconnect ... done
user@server:/volume2/docker$ docker-compose up -d airconnect
WARNING: Some networks were defined but are not used by any service: host
Recreating airconnect ... done
user@server:/volume2/docker$ docker logs -f airconnect
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing... 
Checking for valid arch options
Proceeding with x86-64 arch
--2021-12-11 10:35:50--  https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-x86-64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 694040 (678K) [application/octet-stream]
Saving to: ‘/bin/airupnp-x86-64’

     0K .......... .......... .......... .......... ..........  7% 1.92M 0s
    50K .......... .......... .......... .......... .......... 14% 1.42M 0s
   100K .......... .......... .......... .......... .......... 22% 5.38M 0s
   150K .......... .......... .......... .......... .......... 29% 14.0M 0s
   200K .......... .......... .......... .......... .......... 36% 3.54M 0s
   250K .......... .......... .......... .......... .......... 44% 4.74M 0s
   300K .......... .......... .......... .......... .......... 51% 2.21M 0s
   350K .......... .......... .......... .......... .......... 59% 1.61M 0s
   400K .......... .......... .......... .......... .......... 66% 1.47M 0s
   450K .......... .......... .......... .......... .......... 73% 2.79M 0s
   500K .......... .......... .......... .......... .......... 81% 1.65M 0s
   550K .......... .......... .......... .......... .......... 88% 1.36M 0s
   600K .......... .......... .......... .......... .......... 95%  784K 0s
   650K .......... .......... .......                         100% 4.84M=0.3s

2021-12-11 10:35:51 (1.98 MB/s) - ‘/bin/airupnp-x86-64’ saved [694040/694040]

--2021-12-11 10:35:51--  https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-x86-64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 596440 (582K) [application/octet-stream]
Saving to: ‘/bin/aircast-x86-64’

     0K .......... .......... .......... .......... ..........  8% 15.2M 0s
    50K .......... .......... .......... .......... .......... 17% 1.92M 0s
   100K .......... .......... .......... .......... .......... 25% 1.28M 0s
   150K .......... .......... .......... .......... .......... 34%  112M 0s
   200K .......... .......... .......... .......... .......... 42% 2.90M 0s
   250K .......... .......... .......... .......... .......... 51% 6.67M 0s
   300K .......... .......... .......... .......... .......... 60%  139M 0s
   350K .......... .......... .......... .......... .......... 68%  132M 0s
   400K .......... .......... .......... .......... .......... 77% 9.84M 0s
   450K .......... .......... .......... .......... .......... 85% 2.01M 0s
   500K .......... .......... .......... .......... .......... 94% 77.0M 0s
   550K .......... .......... .......... ..                   100%  134M=0.1s

2021-12-11 10:35:51 (4.65 MB/s) - ‘/bin/aircast-x86-64’ saved [596440/596440]

[cont-init.d] 30-install: exited 1.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-12-11 10:35:52,046 CRIT Supervisor running as root (no user in config file)
2021-12-11 10:35:52,061 INFO supervisord started with pid 304
2021-12-11 10:35:53,063 INFO spawned: 'airupnp-x86-64' with pid 307
2021-12-11 10:35:53,065 INFO spawned: 'aircast-x86-64' with pid 308
2021-12-11 10:35:54,371 INFO success: airupnp-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-11 10:35:54,372 INFO success: aircast-x86-64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
user@server:/volume2/docker$ 

```

**Comment by lollyhero** [comment]
hello  

i use docker on my synology nas, when you change x86-64 to amd64, my airconnect on docker update by watchdog, also arch_VAR changed automaticly to amd64, the log in the docker shown cant find the /bin/airupnp-x86-64, i can show u the log later

**Comment by 1activegeek** [comment]
Again, you are not being clear and answering the question. WHERE are you changing x86-64 to amd64, and WHY are you changing it? You should not have changed anything in the running configuration of your container. The recent changes I made, were to how the docker container is built. You should not be changing anything about this container if you had run it before.

**Comment by lollyhero** [comment]
hello  

after you last change from x86-64 to  amd64. i pull thr dockerimage and update on my nas.

if i run this docker on synology nas using Gui not command, the default value of arch_var is amd64, so when i create this docker without any change 
![image](https://user-images.githubusercontent.com/21963219/145683670-bb1a48f1-fdbc-4de0-bfea-417f7184cd0b.jpeg)
the log shows here
![image](https://user-images.githubusercontent.com/21963219/145683658-7ff8eec5-ce70-4d0f-af06-d18dea8150ca.png)

i must change the arch_var to x86-64 manually.

**Comment by 1activegeek** [comment]
Thank you, now I know what you are changing and that helps clarify the why. I see that there was some scripting I had for pulling the binary that was looking at this ARCH_VAR originally. I'm not sure why but my container was already specifying this so I did not have an issue. I have to adjust this, but I'm having an issue with the auto-builds at the moment. I have what should be working, but for now you can leave that ENV VAR `ARCH_VAR` set as you did. I can hopefully fix the build issue I'm having soon.

**Comment by yougotborked** [comment]
I'm having the same issue, fixed the same way with the env var in my compose.

**Comment by 1activegeek** [comment]
Thanks for the inputs. Working on it as we speak. I know how many people use this, so I'm working to get it fixed today. Had to move over to a new way of running the builder on a weekly basis and had some learning bumps along the way. Should be done in a few hours and pushed to the master branch so that latest pulls a working image.

**Comment by 1activegeek** [comment]
Ok @yougotborked and @lollyhero if you don't mind before I push this to master - can you test running the container using the `:dev` tag? I've updated this to use a new builder and it is working for me. I just want validation beyond myself that it's running correctly. It no longer should have an issue with needing to specify that `ARCH_VAR` env variable. So please remove that if you were using it before testing. Let me know your results.

**Comment by elas123** [comment]
> Ok @yougotborked and @lollyhero if you don't mind before I push this to master - can you test running the container using the `:dev` tag? I've updated this to use a new builder and it is working for me. I just want validation beyond myself that it's running correctly. It no longer should have an issue with needing to specify that `ARCH_VAR` env variable. So please remove that if you were using it before testing. Let me know your results.

I updated using the :dev tag on Unraid it worked. I had same problem as these guys did before

**Comment by lollyhero** [comment]
> Ok @yougotborked and @lollyhero if you don't mind before I push this to master - can you test running the container using the `:dev` tag? I've updated this to use a new builder and it is working for me. I just want validation beyond myself that it's running correctly. It no longer should have an issue with needing to specify that `ARCH_VAR` env variable. So please remove that if you were using it before testing. Let me know your results. 

It worked.

**Comment by yougotborked** [comment]
Can also confirm, worked

**Comment by 1activegeek** [comment]
Thank you all for checking on that. Looks good. I've pushed the change to master, and it has now updated the `:latest` tag as expected. Validated it's working on my side, including using the new `kill` option for services not used (either `AIRUPNP_VAR` for airUPNP or `AIRCAST_VAR` for aircast). Should be good to revert back, docker pull quick for latest update, and then run the container again.

Sorry to anyone landing here after having similar issue - I mis-understood a config I had originally that I changed to "fix" something originally which ended in a broken binary download for standard x86-64/amd64 arch's. ARM and ARM64 shouldn't have been affected.

Knowing it should be working now, I will close this out @lollyhero. If it's not working, feel free to re-open. Thanks for the persistence and getting to the key info for me to see what was breaking. Appreciate it!
