### ISSUE TITLE
Docker on DSM

### ISSUE THREAD

**Issue by crssi** [1activegeek/docker-airconnect#39]
Hi

If I understand correctly I can use this project to AirPlay music from my iOS device  to DSM (assumed that docker correctly runs on it) which can proxy the stream to DNLA enabled audio device on the same network?

I have problems to understand how to configure this docker on DSM correctly and find the instruction not clear.
Can you help?

Thank you,
Cheers

**Comment by 1activegeek** [comment]
Yes that is how it can work. Unfortunately I have no experience on running docker on DSM through Docker interface. So I can't really help you there. I would suggest reading general documentation on running docker containers on DSM as there are plenty out there (full guides that is). That should give you enough knowledge to understand how to run this container.

**Comment by crssi** [comment]
I have also tried with `aircast-win.exe` + dll's in that folder on WIndows 10 (up-to-date) with firewall off.
But on the same network iPhone does not discover it.
I will open isssue at @philippe44 github site.
Will also try with docker on WIndows 10.

Anyway, thank you for fast response and wish you best 👍
