### ISSUE TITLE
New image is published without changes

### ISSUE THREAD

**Issue by mpolden** [1activegeek/docker-airconnect#41]
From what I can tell https://hub.docker.com/r/1activegeek/airconnect is updated once a week, even though there haven't been any changes to either this repository or https://github.com/philippe44/AirConnect.

Why is a new image being published when there aren't any changes?

**Comment by 1activegeek** [comment]
There is a GH action that was created to build every week, pulling the latest stable code from the original developer. It was a quick and dirty solution to fix other issues I had in the past with getting the latest stable code working as expected with the capabilities needed overall for an easy container. If you would like to submit a pull request including a check on the source repo and only complete a fresh build when changes in the source app exist, please feel free and we can test it out.

**Comment by 1activegeek** [comment]
Closing. Recent updates to the workflow will still include updates weekly running, but now spit out versions as well.
