### ISSUE TITLE
Not Working - 404 Error

### ISSUE THREAD

**Issue by TrueCitrus** [1activegeek/docker-airconnect#47]
I get the following error which looks it can’t find AirConnect.  It is showing a 404 error. Any ideas?

[cont-init.d1 10-adduser: exited 0.
[cont-init.d] 30-install: executing.
--2022-11-25 07:06:29--
https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-x86-64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133,
Connecting to raw.githubusercontent.com (raw.githubusercontent.com) 185.199.109.133| :443... connected.
HTTP request sent,
awaiting response...
404 Not Found
2022-11-25 07:06:30 ERROR 404: Not Found.
--2022-11-25 07:06:30--
https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-x86-64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133,
Connecting to raw.githubusercontent.com (raw.githubusercontent.com) |185.199.108.133|:443...
connected.
HTTP request sent,
awaiting response... 404 Not Found
2022-11-25 07:06:30 ERROR 404: Not Found.
[cont-init.d] 30-install: exited 0.
[cont-init.d] 99-custom-scripts: executing.
[custom-init] no custom files found exiting.
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-11-25 07:06:30,712 CRIT Supervisor running as root (no user in config file)
2022-11-25 07:06:30,717 INFO supervisord started with id 238
2022-11-25 07:06:31,718 INFO spawnerr: command at
'/bin/airupnp-x86-64' is not executable
2022-11-25 07:06:31,718 INFO spawnerr: command at
'/bin/aircast-x86-64°
is not executable
2022-11-25 07:06:32,719 INFO spawnerr: command at
2022-11-25 07:06:32,720 INFO spawnerr: command
'/bin/airupnp-x86-64°
is not executable
at
*/bin/aircast-x86-64' is not executable
2022-11-25 07:06:34,722 INFO spawnerr: command at
'/bin/airupnp-x86-64°
is not executable
2022-11-25 07:06:34,723 INFO spawnerr:
command
at
'/bin/aircast-x86-64°
is not executable
2022-11-25 07:06:37,726 INFO spawnerr:
command at
2022-11-25 07:06:37,727 INFO gave up:
'/bin/airupnp-x86-64°
is not executable
airupnp-x86-64 entered FATAL state, too many start retries too quickly

**Comment by 1activegeek** [comment]
It would appear you are running an outdated version of the container. Possibly VERY old as I believe even my previous version before recent changes would actually pull the package as part of the container build, vs container start. Can you try pulling the latest image and the. Re-creating the container?

The issue here based on what I see, is that the old version of my image would pull the actually binary from the author on container start/first run. Recently the author made changes to the naming convention of those binaries, and so this older image won't be able to have the correct binaries inside.

**Comment by TrueCitrus** [comment]
I am using the latest version listed on Dockerhub. How can I make sure I’m on the latest version?

**Comment by 1activegeek** [comment]
By all accounts, that looks to be operating completely correct. The last line of that log shows a successful process spawning. So the container is running, and it looks to be successful. If you are not seeing the targets on your network, then you are likely looking at a network based problem on your side. Unfortunately I can't help much there, but you can search many of the issues on the original github of the code used here. There are also a few people on here who have opened issues that were documented what their issues were when they solved the network side of things.

**Comment by 1activegeek** [comment]
Stale issue with no updates. Please comment again if there is further troubleshooting needed that relates to the container.
