### ISSUE TITLE
Both speakers have the same name

### ISSUE THREAD

**Issue by accpxyz** [1activegeek/docker-airconnect#51]
Dear 1activegeek:
   Before using any parameter, the two speakers can recognize the correct name. When using the - i parameter to generate and change the name in the configuration, and using the - x parameter, the two speaker names are the same. After viewing the xml file, it is found that the udn(uuids) are the same. How to recognize them correctly？

**Comment by 1activegeek** [comment]
Unfortunately that is a question likely better suited to the primary repo of the software in action here. If the container is running, and is even reading a file you're inputting - then there doesn't seem to be anything wrong with the container. Unfortunately I only troubleshoot the container issues that you may have. It sounds like you just need some more help in finding out how to properly identify the targets, and craft the configuration file.

**Comment by accpxyz** [comment]
Thanks for the quick reply
