### ISSUE TITLE
Docker container pulling old version of binaries

### ISSUE THREAD

**Issue by roblewis011** [1activegeek/docker-airconnect#52]
It appears updated binaries are being published here now: https://github.com/philippe44/AirConnect/tree/master/bin

I was seeing many issues with version 1.0.8 which your Dockerfile defaults to, but once I replaced the binary in the container with the newer 1.0.17 version all of my issues went away. Just wanted to make you aware in case you wanted to update your Dockerfile to pull the updated binaries instead.

I did this locally which works great, but your docker variables AIRCAST_VAR and AIRUPNP_VAR don't appear to be working with the changes I made for some reason which I haven't had time to chase down yet.

**Comment by 1activegeek** [comment]
Thanks for the note. It would appear that right around the time that I re-architected my builds, they changed the publishing of releases to now just updating the bins and no releases. I'll ping first and see if that is just an oversight, or if there is another definitive source I can identify like the changelog file to use as the source of identifying what version has been released.

**Comment by meiser79** [comment]
Hi, there're releases again. May I ask to bump airconnect to version 1.1.5?

**Comment by 1activegeek** [comment]
Thanks for the heads up! It looks like the original dev has gotten back to making releases posted, so my action should pickup the build and run automatically again on a weekly schedule. I've "re-run" the previous build that happened a few days ago so it can pickup the new data. Tags and everything look to have worked as expected. Please do let me know if you face any issues.

@roblewis011 - you mentioned some variables weren't working - I'll guess it's possible they were not in the binary I had previously. Let me know if those still aren't working with the latest `1.1.5` version.

**Comment by 1activegeek** [comment]
Closing since there has been no update here, I presume all features that were missing are now working again. Please re-open if there is still an issue.

**Comment by meiser79** [comment]
Sorry for the late feedback, the new containers work fine. Thanks!
