### ISSUE TITLE
airconnect: chromecast device can be detected by iphone,no sound

### ISSUE THREAD

**Issue by Yumega** [1activegeek/docker-airconnect#53]
can see it's playing on chromecast from iphone, but don't have sound

**Comment by 1activegeek** [comment]
Are there any errors being reported from in the docker logs for the container? Unless there are errors, then you are likely facing issues on your network blocking the playback. This is not something container related and you may be better suited reading through issues on the Airconnect project for similar issues with playback. Unfortunately I only support the container itself, and from the sounds of it the container is working as expected.

**Comment by Yumega** [comment]
> Are there any errors being reported from in the docker logs for the container? Unless there are errors, then you are likely facing issues on your network blocking the playback. This is not something container related and you may be better suited reading through issues on the Airconnect project for similar issues with playback. Unfortunately I only support the container itself, and from the sounds of it the container is working as expected.

stdout: [custom-init] No custom files found, skipping...
stdout: [ls.io-init] done.
stdout: 2023-07-08 16:25:44,722 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
stdout: 2023-07-08 16:25:44,725 INFO supervisord started with pid 158
stdout: 2023-07-08 16:25:45,728 INFO spawned: 'aircast-linux-x86_64' with pid 159
stdout: 2023-07-08 16:25:45,730 INFO spawned: 'airupnp-linux-x86_64' with pid 160
stdout: 2023-07-08 16:25:46,764 INFO success: aircast-linux-x86_64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stdout: 2023-07-08 16:25:46,764 INFO success: airupnp-linux-x86_64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by 1activegeek** [comment]
No errors I can see about the service. It appears to be starting as expected and stays running as expected. There is no issue here to resolve about the container.

**Comment by 1activegeek** [comment]
Stale issue. Closing. Please re-open or file new if there is followup here.
