### ISSUE TITLE
Bring back arm/v7 support

### ISSUE THREAD

**Issue by sidevesh** [1activegeek/docker-airconnect#55]
I created a fork at https://github.com/sidevesh/docker-airconnect and changed the base to `FROM lsiobase/ubuntu:jammy-05e08486-ls73` and with that I was able to get the latest version workin on arm/v7,
can you bring back arm/v7 support with a separate Dockerfile for arm/v7 that uses this older image,
I know its not preferred but atleast keeps things working for those of us stuck on arm/v7 for now.

**Comment by sidevesh** [comment]
Raised a PR for this #56

**Comment by 1activegeek** [comment]
Unfortunately this will require more work I think than a quick update/change. I streamlined the deployment with a single Dockerfile. Setting the image used there, would affect all other platforms. Adding a separate file, introduces more complexity and management. 

I'd suggest the best option would be either to keep the version you've created for use, and I'd be happy to link it for reference for anyone on ARMv7, or to just pin your airconnect container deploy to the last version before v7 was removed (1activegeek/airconnect:1.0.8). 

Unfortunately for me, I don't have many cycles to dedicate to ensure there are no issues in re-architecting my build to support. And without having a v7 device myself to test with, I can't guarantee outputs currently are working properly very easily. My biggest concern is that armv7 is losing support overall, and incompatibilities are sure to creep in.

**Comment by sidevesh** [comment]
Sure, I figured it was gonna take a bit more effort than I had thought and the PR I had opened was broken so I closed it,
you can maybe add a link to https://hub.docker.com/repository/docker/sidevesh/airconnect,
this is just my fork of your repo with linuxserver ubuntu:jammy base image pinned to the last armv7 supported version

**Comment by 1activegeek** [comment]
@sidevesh absolutely! I appreciate the thought and effort to help support it. I'm quite particular overall though and want to be sure anything I'm backing has 100% validity and support. But thanks for the attempt and at least having the link will be helpful for anyone who catches my headline about ARMv7 support being deprecated. And thanks for being a consumer.

Honestly I'll leave this open so it's on my radar in case I'm able to come back and give it some love. I try to review the open request I have here every once and awhile to see if I can add some polish to the final product. It's a worthy exercise to see if I can't optimize and create a single docker file somehow with support for armv7 somehow.

**Comment by 1activegeek** [comment]
Updated the note about ARMv7 support. Highlighting the option to pin to the 1.0.8 version as well as link to your container. 👍🏻

**Comment by sidevesh** [comment]
@1activegeek I have migrated my setup to arm64 too, I will keep the existing armv7 image up on DockerHub but it won't be receiving new updates since I won't be able to test changes,
closing this issue.
