### ISSUE TITLE
Output audio on airplay device, which are linked to Sonos S1 devices, is bad.   

### ISSUE THREAD

**Issue by dm2310** [1activegeek/docker-airconnect#59]
* Output audio from Synology Audio station to upnp devices, which are linked to Sonos S1 devices, is good.
* Output audio from Synology Audio station to Airplay devices, which are linked to Sonos S1 devices, is bad.
  The output audio is being skipped randomly and has a lot of click noises.  Adjusting the latency airpnp won't resolve problem, other   adjustment with "drift" parameter won't help neither.  Airpnp log shows no error.  My system is DS3622x. 
  
I stopped the airconnect in docker hub and then installed the airconnect from https://github.com/eizedev/AirConnect-Synology.  Everything works with airconnect from Eizedev release.  

Hope this will help with your own tests to address the issue.

Thanks

**Comment by 1activegeek** [comment]
Very sorry I never responded back when this was posted. Apologies, I think I must have gotten sidetracked and not come back to this. 

I'm not quite sure what could be going wrong, but I'd suggest it has something to do with specifically the Synology Audio talking to the container versus the Synology Audio talking to another Synology service (the plugin you linked) that is causing you issues. I play from devices in my home, to airplay targets, with this container running on my Synology DS1821+ and have no issues. So I wouldn't say there is a specific issue that I'm aware of with running this on a Synology. If there is a minor niche problem with Synology Audio, this container, and Airplay targets - then perhaps I can document it as a known issue. 

Perhaps if you can take a test run, try using this container but NOT using Synology Audio Station as the source. If this works without issue, then I'd for sure say it has something to do with Synology Audio Station specifically. Unfortunately it's not something large scale enough of an issue that I think I'll be able to debug and figure out.

**Comment by 1activegeek** [comment]
Marking closed as this is stale and there was no response to the suggest actions. Please re-open if you can provide more info/context.
